# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balanceador.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='balanceador.proto',
  package='balanceoRPC',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x62\x61lanceador.proto\x12\x0b\x62\x61lanceoRPC\"\x1b\n\x08peticion\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"%\n\trespuesta\x12\x18\n\x10mensajeRespuesta\x18\x01 \x01(\t2K\n\x08\x42\x61lanceo\x12?\n\x0crecibirOrden\x12\x15.balanceoRPC.peticion\x1a\x16.balanceoRPC.respuesta\"\x00\x62\x06proto3'
)




_PETICION = _descriptor.Descriptor(
  name='peticion',
  full_name='balanceoRPC.peticion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='balanceoRPC.peticion.mensaje', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=61,
)


_RESPUESTA = _descriptor.Descriptor(
  name='respuesta',
  full_name='balanceoRPC.respuesta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensajeRespuesta', full_name='balanceoRPC.respuesta.mensajeRespuesta', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['peticion'] = _PETICION
DESCRIPTOR.message_types_by_name['respuesta'] = _RESPUESTA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

peticion = _reflection.GeneratedProtocolMessageType('peticion', (_message.Message,), {
  'DESCRIPTOR' : _PETICION,
  '__module__' : 'balanceador_pb2'
  # @@protoc_insertion_point(class_scope:balanceoRPC.peticion)
  })
_sym_db.RegisterMessage(peticion)

respuesta = _reflection.GeneratedProtocolMessageType('respuesta', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTA,
  '__module__' : 'balanceador_pb2'
  # @@protoc_insertion_point(class_scope:balanceoRPC.respuesta)
  })
_sym_db.RegisterMessage(respuesta)



_BALANCEO = _descriptor.ServiceDescriptor(
  name='Balanceo',
  full_name='balanceoRPC.Balanceo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=102,
  serialized_end=177,
  methods=[
  _descriptor.MethodDescriptor(
    name='recibirOrden',
    full_name='balanceoRPC.Balanceo.recibirOrden',
    index=0,
    containing_service=None,
    input_type=_PETICION,
    output_type=_RESPUESTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BALANCEO)

DESCRIPTOR.services_by_name['Balanceo'] = _BALANCEO

# @@protoc_insertion_point(module_scope)
