# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distribuidos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='distribuidos.proto',
  package='archivosRPC',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x64istribuidos.proto\x12\x0b\x61rchivosRPC\"4\n\rautenticacion\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x12\n\ncontrasena\x18\x02 \x01(\t\"2\n\x08peticion\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x15\n\rnombreArchivo\x18\x02 \x01(\t\"T\n\x11peticionEscritura\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x15\n\rnombreArchivo\x18\x02 \x01(\t\x12\x17\n\x0fopcionEscritura\x18\x03 \x01(\t\"N\n\x08renombre\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x15\n\rnombreArchivo\x18\x02 \x01(\t\x12\x1a\n\x12nombreNuevoArchivo\x18\x03 \x01(\t\"\x1b\n\trespuesta\x12\x0e\n\x06\x65stado\x18\x01 \x01(\x05\"\x1e\n\rpeticionDatos\x12\r\n\x05\x64\x61tos\x18\x01 \x01(\t\"*\n\x05lista\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x11\n\tisArchivo\x18\x02 \x01(\x08\x32\xe3\x05\n\x08\x41rchivos\x12?\n\x07logging\x12\x1a.archivosRPC.autenticacion\x1a\x16.archivosRPC.respuesta\"\x00\x12\x39\n\x06\x63reate\x12\x15.archivosRPC.peticion\x1a\x16.archivosRPC.respuesta\"\x00\x12:\n\x07preread\x12\x15.archivosRPC.peticion\x1a\x16.archivosRPC.respuesta\"\x00\x12=\n\x04read\x12\x15.archivosRPC.peticion\x1a\x1a.archivosRPC.peticionDatos\"\x00\x30\x01\x12\x44\n\x08prewrite\x12\x1e.archivosRPC.peticionEscritura\x1a\x16.archivosRPC.respuesta\"\x00\x12?\n\x05write\x12\x1a.archivosRPC.peticionDatos\x1a\x16.archivosRPC.respuesta\"\x00(\x01\x12\x39\n\x06rename\x12\x15.archivosRPC.renombre\x1a\x16.archivosRPC.respuesta\"\x00\x12\x39\n\x06remove\x12\x15.archivosRPC.peticion\x1a\x16.archivosRPC.respuesta\"\x00\x12\x38\n\x05mkdir\x12\x15.archivosRPC.peticion\x1a\x16.archivosRPC.respuesta\"\x00\x12\x38\n\x05rmdir\x12\x15.archivosRPC.peticion\x1a\x16.archivosRPC.respuesta\"\x00\x12\x38\n\x07readdir\x12\x15.archivosRPC.peticion\x1a\x12.archivosRPC.lista\"\x00\x30\x01\x12\x35\n\x02\x63\x64\x12\x15.archivosRPC.peticion\x1a\x16.archivosRPC.respuesta\"\x00\x62\x06proto3'
)




_AUTENTICACION = _descriptor.Descriptor(
  name='autenticacion',
  full_name='archivosRPC.autenticacion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='usuario', full_name='archivosRPC.autenticacion.usuario', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contrasena', full_name='archivosRPC.autenticacion.contrasena', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=87,
)


_PETICION = _descriptor.Descriptor(
  name='peticion',
  full_name='archivosRPC.peticion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='usuario', full_name='archivosRPC.peticion.usuario', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombreArchivo', full_name='archivosRPC.peticion.nombreArchivo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=139,
)


_PETICIONESCRITURA = _descriptor.Descriptor(
  name='peticionEscritura',
  full_name='archivosRPC.peticionEscritura',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='usuario', full_name='archivosRPC.peticionEscritura.usuario', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombreArchivo', full_name='archivosRPC.peticionEscritura.nombreArchivo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opcionEscritura', full_name='archivosRPC.peticionEscritura.opcionEscritura', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=225,
)


_RENOMBRE = _descriptor.Descriptor(
  name='renombre',
  full_name='archivosRPC.renombre',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='usuario', full_name='archivosRPC.renombre.usuario', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombreArchivo', full_name='archivosRPC.renombre.nombreArchivo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombreNuevoArchivo', full_name='archivosRPC.renombre.nombreNuevoArchivo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=305,
)


_RESPUESTA = _descriptor.Descriptor(
  name='respuesta',
  full_name='archivosRPC.respuesta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='estado', full_name='archivosRPC.respuesta.estado', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=334,
)


_PETICIONDATOS = _descriptor.Descriptor(
  name='peticionDatos',
  full_name='archivosRPC.peticionDatos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='datos', full_name='archivosRPC.peticionDatos.datos', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=366,
)


_LISTA = _descriptor.Descriptor(
  name='lista',
  full_name='archivosRPC.lista',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='archivosRPC.lista.nombre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isArchivo', full_name='archivosRPC.lista.isArchivo', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=410,
)

DESCRIPTOR.message_types_by_name['autenticacion'] = _AUTENTICACION
DESCRIPTOR.message_types_by_name['peticion'] = _PETICION
DESCRIPTOR.message_types_by_name['peticionEscritura'] = _PETICIONESCRITURA
DESCRIPTOR.message_types_by_name['renombre'] = _RENOMBRE
DESCRIPTOR.message_types_by_name['respuesta'] = _RESPUESTA
DESCRIPTOR.message_types_by_name['peticionDatos'] = _PETICIONDATOS
DESCRIPTOR.message_types_by_name['lista'] = _LISTA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

autenticacion = _reflection.GeneratedProtocolMessageType('autenticacion', (_message.Message,), {
  'DESCRIPTOR' : _AUTENTICACION,
  '__module__' : 'distribuidos_pb2'
  # @@protoc_insertion_point(class_scope:archivosRPC.autenticacion)
  })
_sym_db.RegisterMessage(autenticacion)

peticion = _reflection.GeneratedProtocolMessageType('peticion', (_message.Message,), {
  'DESCRIPTOR' : _PETICION,
  '__module__' : 'distribuidos_pb2'
  # @@protoc_insertion_point(class_scope:archivosRPC.peticion)
  })
_sym_db.RegisterMessage(peticion)

peticionEscritura = _reflection.GeneratedProtocolMessageType('peticionEscritura', (_message.Message,), {
  'DESCRIPTOR' : _PETICIONESCRITURA,
  '__module__' : 'distribuidos_pb2'
  # @@protoc_insertion_point(class_scope:archivosRPC.peticionEscritura)
  })
_sym_db.RegisterMessage(peticionEscritura)

renombre = _reflection.GeneratedProtocolMessageType('renombre', (_message.Message,), {
  'DESCRIPTOR' : _RENOMBRE,
  '__module__' : 'distribuidos_pb2'
  # @@protoc_insertion_point(class_scope:archivosRPC.renombre)
  })
_sym_db.RegisterMessage(renombre)

respuesta = _reflection.GeneratedProtocolMessageType('respuesta', (_message.Message,), {
  'DESCRIPTOR' : _RESPUESTA,
  '__module__' : 'distribuidos_pb2'
  # @@protoc_insertion_point(class_scope:archivosRPC.respuesta)
  })
_sym_db.RegisterMessage(respuesta)

peticionDatos = _reflection.GeneratedProtocolMessageType('peticionDatos', (_message.Message,), {
  'DESCRIPTOR' : _PETICIONDATOS,
  '__module__' : 'distribuidos_pb2'
  # @@protoc_insertion_point(class_scope:archivosRPC.peticionDatos)
  })
_sym_db.RegisterMessage(peticionDatos)

lista = _reflection.GeneratedProtocolMessageType('lista', (_message.Message,), {
  'DESCRIPTOR' : _LISTA,
  '__module__' : 'distribuidos_pb2'
  # @@protoc_insertion_point(class_scope:archivosRPC.lista)
  })
_sym_db.RegisterMessage(lista)



_ARCHIVOS = _descriptor.ServiceDescriptor(
  name='Archivos',
  full_name='archivosRPC.Archivos',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=413,
  serialized_end=1152,
  methods=[
  _descriptor.MethodDescriptor(
    name='logging',
    full_name='archivosRPC.Archivos.logging',
    index=0,
    containing_service=None,
    input_type=_AUTENTICACION,
    output_type=_RESPUESTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='create',
    full_name='archivosRPC.Archivos.create',
    index=1,
    containing_service=None,
    input_type=_PETICION,
    output_type=_RESPUESTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='preread',
    full_name='archivosRPC.Archivos.preread',
    index=2,
    containing_service=None,
    input_type=_PETICION,
    output_type=_RESPUESTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='read',
    full_name='archivosRPC.Archivos.read',
    index=3,
    containing_service=None,
    input_type=_PETICION,
    output_type=_PETICIONDATOS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='prewrite',
    full_name='archivosRPC.Archivos.prewrite',
    index=4,
    containing_service=None,
    input_type=_PETICIONESCRITURA,
    output_type=_RESPUESTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='write',
    full_name='archivosRPC.Archivos.write',
    index=5,
    containing_service=None,
    input_type=_PETICIONDATOS,
    output_type=_RESPUESTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='rename',
    full_name='archivosRPC.Archivos.rename',
    index=6,
    containing_service=None,
    input_type=_RENOMBRE,
    output_type=_RESPUESTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='remove',
    full_name='archivosRPC.Archivos.remove',
    index=7,
    containing_service=None,
    input_type=_PETICION,
    output_type=_RESPUESTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='mkdir',
    full_name='archivosRPC.Archivos.mkdir',
    index=8,
    containing_service=None,
    input_type=_PETICION,
    output_type=_RESPUESTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='rmdir',
    full_name='archivosRPC.Archivos.rmdir',
    index=9,
    containing_service=None,
    input_type=_PETICION,
    output_type=_RESPUESTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='readdir',
    full_name='archivosRPC.Archivos.readdir',
    index=10,
    containing_service=None,
    input_type=_PETICION,
    output_type=_LISTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='cd',
    full_name='archivosRPC.Archivos.cd',
    index=11,
    containing_service=None,
    input_type=_PETICION,
    output_type=_RESPUESTA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARCHIVOS)

DESCRIPTOR.services_by_name['Archivos'] = _ARCHIVOS

# @@protoc_insertion_point(module_scope)
